trigger:
  - event: ["push", "pull_request"]
    branch: ["main"]

engine: microvm

dependencies:
  nixpkgs:
    - rustc
    - cargo

environment:
  CARGO_TERM_COLOR: always

steps:
  - name: rustfmt
    command: cargo fmt --all -- --check
  - name: clippy
    command: cargo clippy --workspace --all-targets -- -D warnings
